### PR TITLE
290: fix review dialog crash

### LINKED ISSUE #290: android.view.WindowManager$BadTokenException
android.view.WindowManager$BadTokenException: 
  at android.view.ViewRootImpl.setView (ViewRootImpl.java:1133)
  at android.view.WindowManagerGlobal.addView (WindowManagerGlobal.java:409)
  at android.view.WindowManagerImpl.addView (WindowManagerImpl.java:111)
  at android.app.Dialog.show (Dialog.java:342)
  at com.omen273.crossLingo.GameActivity.showFinishGameDialog (GameActivity.kt:459)
  at com.omen273.crossLingo.GameActivity.showFinishGameDialog$default (GameActivity.kt:448)
  at com.omen273.crossLingo.GameActivity.requestReview$lambda-28$lambda-27 (GameActivity.kt:470)
  at com.omen273.crossLingo.GameActivity.lambda$KVyn4uMdeSTHSYSSU0V-CYvFpsU (Unknown Source)
  at com.omen273.crossLingo.-$$Lambda$GameActivity$KVyn4uMdeSTHSYSSU0V-CYvFpsU.onComplete (Unknown Source:2)
  at com.google.android.play.core.tasks.zza.run
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:236)
  at android.app.ActivityThread.main (ActivityThread.java:8056)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:656)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:967)

### PR DESCRIPTION
**Pull request by greenEkatherine**
Fixes #290

### CODE REVIEW

File: app/src/main/java/com/omen273/crossLingo/GameActivity.kt [hunk 1]
```diff
@@ -584,7 +586,7 @@ class GameActivity : AppCompatActivity(), CrosswordView.OnLongPressListener,
         val path = File(filesDir, "solved_crossword_number.json")
         if (path.exists()) {
             val number = readSolvedCrosswordNumberToFile(path)
-            if (number == 3 || number % 100 == 0) requestReview()
+            if (number >=0/*== 3 || number % 100 == 0*/) requestReview()
```
Comment (omen273) [inline app/src/main/java/com/omen273/crossLingo/GameActivity.kt:589]: Please return it back

**Review by omen273 — CHANGES_REQUESTED** [review]
Please address my comment

File: app/src/main/java/com/omen273/crossLingo/GameActivity.kt (hunk 1 above)
Comment (greenEkatherine) [reply app/src/main/java/com/omen273/crossLingo/GameActivity.kt]: done

**Review by omen273 — APPROVED** [review]
