### PR TITLE
303: fix starts number after solving and improve test

### LINKED ISSUE #303: Check number of stars after solving crossword with non-free tips if star indicator is free
Please check that you have right number of stars if you solve crossword with help of non-free tips if star indicator is free. I think you need to update starNumber in this case

_Originally posted by @omen273 in https://github.com/omen273/crosswordApp/pull/302#r795170641_

### PR DESCRIPTION
**Pull request by greenEkatherine**
Fixes #303

### CODE REVIEW

File: app/src/androidTest/java/com/omen273/crossLingo/FreeClueInstrumentedTest.kt [hunk 1]
```diff
@@ -63,13 +64,49 @@ class FreeClueInstrumentedTest : TestBaseClass() {
...
+        menuClick(R.string.solve_word_free, R.id.menu_solve_word)
+
+        // 8 more words to solve all except one word
+        for (i in 0..7)
+        {
+            menuClick(R.string.solve_word, R.id.menu_solve_word)
+            starNumber -= GameActivity.WORD_OPEN_PRICE
+        }
+
+        val start5 = System.currentTimeMillis()
```
Comment (omen273) [inline app/src/androidTest/java/com/omen273/crossLingo/FreeClueInstrumentedTest.kt:95]: Please test also that we have free tip for cell

Comment (greenEkatherine) [reply app/src/androidTest/java/com/omen273/crossLingo/FreeClueInstrumentedTest.kt:109]: done

**Review by omen273 — APPROVED** [review]
