### PR TITLE
301: fix free clue logic and crash with menu items

### LINKED ISSUE #301: Fix java.lang.NumberFormatException
https://dev.azure.com/warpedomen/warpedomen/_build/results?buildId=730&view=ms.vss-test-web.build-test-results-tab&runId=9292&resultId=100020&paneView=debug It looks like it is possible to have FREE word in 579 line GameActivity. It is need to check that it is possible to transform string to int otherwise get starNumber from class and use it

### PR DESCRIPTION
**Pull request by greenEkatherine**
Fixes #301

### CODE REVIEW

File: app/src/androidTest/java/com/omen273/crossLingo/FreeClueInstrumentedTest.kt [hunk 1]
```diff
@@ -11,6 +11,9 @@ import org.junit.Test
 
 class FreeClueInstrumentedTest : TestBaseClass() {
 
+    private val LETTER_OPEN_PRICE: Int = 1
```
Comment (omen273) [inline app/src/androidTest/java/com/omen273/crossLingo/FreeClueInstrumentedTest.kt:14]: Please get it from GameActivity

File: app/src/main/java/com/omen273/crossLingo/GameActivity.kt [hunk 2]
```diff
@@ -576,7 +573,8 @@ class GameActivity : AppCompatActivity(), CrosswordView.OnLongPressListener,
         }
 
     override fun onCrosswordSolved(view: CrosswordView) {
-        star_number.text = (star_number.text.toString().toInt() + BONUS_ON_SOLVE).toString()
+        star_number.text = ((star_number.text.toString().toIntOrNull() ?: starNumber) + BONUS_ON_SOLVE).toString()
```
Comment (omen273) [inline app/src/main/java/com/omen273/crossLingo/GameActivity.kt:576]: Please check that you have right number of stars if you solve crossword with help of non-free tips if star indicator is free. I think you need to update starNumber in this case

Comment (omen273) [reply app/src/main/java/com/omen273/crossLingo/GameActivity.kt:576]: And add test on it

Comment (omen273) [reply app/src/main/java/com/omen273/crossLingo/GameActivity.kt:576]: It should work so please add or modify test in separate ticket

**Review by omen273 — APPROVED** [review]
